plugins {
    id "java-library"
    id "maven-publish"
    id "com.timgroup.jarmangit" version "1.1.86"
    id "java-common-conventions"
    id "java-publishing-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

jar {
    manifest { 
        attributes(
            'Automatic-Module-Name': 'com.timgroup.tucker'
        )
    }
}

// some of these dependencies are optional, in that they are needed to build, but might not be needed to run; Gradle does currently let us say so
dependencies {
    implementation libs.slf4j.api
    compileOnly "javax.servlet:javax.servlet-api:3.0.1"
    implementation platform(libs.jackson.bom)
    implementation "com.fasterxml.jackson.core:jackson-core"
    api "io.dropwizard.metrics:metrics-core:3.2.0"
    implementation "io.prometheus:simpleclient_dropwizard:0.9.0"
    implementation "io.prometheus:simpleclient:0.9.0"

    testImplementation "javax.servlet:javax.servlet-api:3.0.1"
    testImplementation libs.bundles.junit
    testImplementation "com.fasterxml.jackson.core:jackson-databind"
    testImplementation "com.google.guava:guava:28.0-jre"

    testRuntimeOnly libs.slf4j.simple
}
