plugins {
    id "application"
    id "java-common-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

ext {
    httpPort = 8888
}

tasks.named("jar").configure {
    manifest {
        attributes(
                'Automatic-Module-Name': 'com.timgroup.tucker.demo'
        )
    }
}

dependencies {
    implementation project(":")
    implementation libs.slf4j.api

    runtimeOnly libs.slf4j.simple

    implementation platform(libs.jetty.bom)
    implementation "org.eclipse.jetty:jetty-server"
    implementation "org.eclipse.jetty:jetty-servlet"
    implementation libs.commons.io
}

mainClassName = 'infrastructure.JettyLauncher'

run {
    args = [httpPort.toString()]
}
