plugins {
    id "java"
    id "java-common-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

tasks.named("jar").configure {
    manifest {
        attributes(
                'Automatic-Module-Name': 'com.timgroup.tucker.test.jetty'
        )
    }
}

dependencies {
    testImplementation project(":")
    testImplementation libs.slf4j.api

    testRuntimeOnly libs.slf4j.simple

    testImplementation libs.bundles.junit
    testImplementation platform(libs.jetty.bom)
    testImplementation "org.eclipse.jetty:jetty-server"
    testImplementation "org.eclipse.jetty:jetty-servlet"
    testImplementation "org.apache.httpcomponents:httpclient:4.5.12"
}
